### ISSUE TITLE
Bug with display of multiple instances of widget on the same form

### ISSUE THREAD

**Issue by euknyaz** [euknyaz/oc-relation-dynamic-dropdown-formwidget#3]
```
Given I am on the Form with 2 dynamic-relation-dropdown fields
- User field
- Product field
And I choose values for Product relation (second field) with autocomplete 
Then I expect to see list of products
Actual: I see list of users instead of products. 
            E.g. I always see results of the first field.
```

Explanation:
* This is due to strange behavior of OctoberCMS AJAX handlers, where variables like $this->valueFrom, $this->formField always pre-populated with the first field.
* Need to implement workaround to receive field name from additional post parameter.

**Comment by msomma** [comment]
Dear euknyaz, first of all great job for tue plugin. 
I just reproduced bug, please find workaround or if you want I can help.
I also added ability to reset inserted value if you are interested in.. 
I will soon add X icon to reset value near dropdown icon, sometimes is very useful to remove inserted value..

To achieve modification I moved control partial in a widget directory:

   public function render()
    {
        $this->prepareVars();
        //return $this->makePartial('~/modules/backend/formwidgets/relation/partials/_relation.htm');
        return $this->makePartial('plugins/euknyaz/relationdynamicdropdown/widgets/select2/_relation.htm');
    }


<div class="relation-widget" id="<?= $this->getId() ?>">
    <?= $this->makePartial('~/modules/backend/widgets/form/partials/_field_'.$field->type.'.htm', ['field' => $field]) ?>
    <a href="javascript:$('#Form-field-Item-worker').empty();">reset</a>
</div>

Regards

**Comment by msomma** [comment]
<div class="relation-widget" id="<?= $this->getId() ?>">
    <?= $this->makePartial('~/modules/backend/widgets/form/partials/_field_'.$field->type.'.htm', ['field' => $field]) ?>
    <a href="javascript:$('#...').empty();">reset</a>
</div>
